# Generated by Django 3.1.6 on 2021-02-19 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='is_qualify',
            field=models.BooleanField(default=True),
        ),
    ]
