# Generated by Django 3.1.6 on 2021-02-19 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='tumbbnail',
            field=models.ImageField(blank=True, null=True, upload_to='blog_thumbnail/%Y/%m/%d'),
        ),
    ]
