# Generated by Django 3.1.6 on 2021-02-19 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_tag_users'),
        ('blog', '0004_auto_20210219_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='blog_category', to='main.category'),
        ),
    ]
