# Generated by Django 3.1.6 on 2021-02-18 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210218_2228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='users',
        ),
    ]
