# Generated by Django 3.1.6 on 2021-02-14 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='updated_date',
            field=models.DateTimeField(),
        ),
    ]
