# Generated by Django 3.1.6 on 2021-02-18 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210218_2156'),
        ('courses', '0004_auto_20210218_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='Course_tags', to='main.Tag'),
        ),
    ]
