# Generated by Django 3.1.6 on 2021-02-19 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_tag_users'),
        ('courses', '0006_auto_20210219_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='tags',
            field=models.ManyToManyField(related_name='Course_tags', to='main.Tag'),
        ),
    ]
